name: Release

on:
  release:
    types: [published]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Version
#         id: version
#         run: echo "version=1.0.${{ github.run_number }}" >> $GITHUB_ENV
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Docker Login
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USER }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: doink/pg-backup:latest, doink/pg-backup:${{env.version}}
#           platforms: linux/amd64,linux/arm64
#       - name: Docker Hub Description
#         uses: peter-evans/dockerhub-description@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USER }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}
#           repository: doink/pg-backup
